# Generated by Django 3.2.9 on 2021-11-19 20:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.TextField(default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_finished', models.DateTimeField()),
                ('process', models.TextField(default='pickingUp', max_length=50)),
                ('pickup_coord', models.TextField(max_length=50, null=True)),
                ('dest_coord', models.TextField(max_length=50, null=True)),
                ('distance', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('active_status', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
                ('vehicle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('detail', models.TextField(default='', max_length=200)),
                ('vehicle_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
            ],
        ),
    ]
