# Generated by Django 3.2.9 on 2021-11-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='is_deleted',
            new_name='is_available',
        ),
        migrations.AddField(
            model_name='rental',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
    ]
