# Generated by Django 3.2.9 on 2021-11-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='time_finished',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
