# Generated by Django 3.2.9 on 2021-11-11 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('api', '0002_auto_20211111_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
