# Generated by Django 3.2.9 on 2021-11-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_rental_time_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='distance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rental',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
