# Generated by Django 3.2 on 2021-11-13 22:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211111_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_available',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.TextField(default='Active', max_length=20),
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('detail', models.TextField(default='', max_length=200)),
                ('vehicle_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
            ],
        ),
    ]
