# Generated by Django 3.2.9 on 2021-11-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211113_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='year',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.TextField(default='', max_length=50),
        ),
    ]
